### ISSUE TITLE
Creating and destroying a lot of `NoTitlebarTk` (x11) crashes

### ISSUE THREAD

**Issue by TheLizzard** [TheLizzard/BetterTk#1]
Creating and destroying around 240 `NoTitlebarTk` windows crashes:
```
ProblemType: Crash
Architecture: amd64
CrashCounter: 1
CurrentDesktop: ubuntu:GNOME
Date: Wed Sep  8 12:31:23 2021
DistroRelease: Ubuntu 21.04
ExecutablePath: /usr/bin/python3.9
ExecutableTimestamp: 1620721237
ProcCmdline: /usr/bin/python3 -c __import__('idlelib.run').run.main(True) 59853
ProcCwd: /bettertk/bettertk
ProcEnviron:
 LANGUAGE=en_GB:en
 PATH=(custom, user)
 XDG_RUNTIME_DIR=<set>
 LANG=en_GB.UTF-8
 SHELL=/bin/bash
ProcMaps:
 ...
ProcStatus:
 Name:	python3
 Umask:	0002
 State:	S (sleeping)
 Tgid:	12795
 Ngid:	0
 Pid:	12795
 PPid:	8463
 TracerPid:	0
 Uid:	1000	1000	1000	1000
 Gid:	1000	1000	1000	1000
 FDSize:	256
 Groups:	4 24 27 30 46 121 132 133 1000 
 NStgid:	12795
 NSpid:	12795
 NSpgid:	6686
 NSsid:	6686
 VmPeak:	  181296 kB
 VmSize:	  143540 kB
 VmLck:	       0 kB
 VmPin:	       0 kB
 VmHWM:	   42020 kB
 VmRSS:	   41920 kB
 RssAnon:	   28568 kB
 RssFile:	   13352 kB
 RssShmem:	       0 kB
 VmData:	   44744 kB
 VmStk:	     132 kB
 VmExe:	    2620 kB
 VmLib:	    7792 kB
 VmPTE:	     160 kB
 VmSwap:	       0 kB
 HugetlbPages:	       0 kB
 CoreDumping:	1
 THP_enabled:	1
 Threads:	3
 SigQ:	0/28841
 SigPnd:	0000000000000000
 ShdPnd:	0000000000000000
 SigBlk:	0000000000000000
 SigIgn:	0000000001001000
 SigCgt:	0000000180000002
 CapInh:	0000000000000000
 CapPrm:	0000000000000000
 CapEff:	0000000000000000
 CapBnd:	000001ffffffffff
 CapAmb:	0000000000000000
 NoNewPrivs:	0
 Seccomp:	0
 Seccomp_filters:	0
 Speculation_Store_Bypass:	thread vulnerable
 SpeculationIndirectBranch:	conditional enabled
 Cpus_allowed:	ffff
 Cpus_allowed_list:	0-15
 Mems_allowed:	00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000001
 Mems_allowed_list:	0
 voluntary_ctxt_switches:	57816
 nonvoluntary_ctxt_switches:	1486
Signal: 11
Uname: Linux 5.14.0-051400rc7-generic x86_64
UserGroups: adm cdrom dip lpadmin lxd plugdev sambashare sudo
CoreDump: base64
 ...
ApportVersion: 2.20.11-0ubuntu65.1
CasperMD5CheckResult: pass
Dependencies:
 ...
Disassembly:
 => 0x7f421339e012 <XQueryTree+50>:	mov    0x968(%rdi),%rax
    0x7f421339e019 <XQueryTree+57>:	test   %rax,%rax
    0x7f421339e01c <XQueryTree+60>:	je     0x7f421339e020 <XQueryTree+64>
    0x7f421339e01e <XQueryTree+62>:	call   *(%rax)
    0x7f421339e020 <XQueryTree+64>:	mov    $0x8,%edx
    0x7f421339e025 <XQueryTree+69>:	mov    $0xf,%esi
    0x7f421339e02a <XQueryTree+74>:	mov    %rbp,%rdi
    0x7f421339e02d <XQueryTree+77>:	call   0x7f42133a8f30 <_XGetRequest>
    0x7f421339e032 <XQueryTree+82>:	mov    %rsp,%rsi
    0x7f421339e035 <XQueryTree+85>:	xor    %ecx,%ecx
    0x7f421339e037 <XQueryTree+87>:	xor    %edx,%edx
    0x7f421339e039 <XQueryTree+89>:	mov    %r12d,0x4(%rax)
    0x7f421339e03d <XQueryTree+93>:	mov    %rbp,%rdi
    0x7f421339e040 <XQueryTree+96>:	call   0x7f42133aa250 <_XReply>
    0x7f421339e045 <XQueryTree+101>:	mov    %eax,%r12d
    0x7f421339e048 <XQueryTree+104>:	test   %eax,%eax
InstallationDate: Installed on 2021-08-24 (14 days ago)
InstallationMedia: Ubuntu 21.04 "Hirsute Hippo" - Release amd64 (20210420)
JournalErrors:
 ...
Package: python3.9-minimal 3.9.5-3~21.04
PackageArchitecture: amd64
ProcCpuinfoMinimal:
 processor	: 11
 vendor_id	: AuthenticAMD
 cpu family	: 23
 model		: 104
 model name	: AMD Ryzen 5 5500U with Radeon Graphics
 stepping	: 1
 microcode	: 0x8608103
 cpu MHz		: 2100.000
 cache size	: 512 KB
 physical id	: 0
 siblings	: 12
 core id		: 6
 cpu cores	: 6
 apicid		: 13
 initial apicid	: 13
 fpu		: yes
 fpu_exception	: yes
 cpuid level	: 16
 wp		: yes
 flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good nopl nonstop_tsc cpuid extd_apicid aperfmperf rapl pni pclmulqdq monitor ssse3 fma cx16 sse4_1 sse4_2 movbe popcnt aes xsave avx f16c rdrand lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw ibs skinit wdt tce topoext perfctr_core perfctr_nb bpext perfctr_llc mwaitx cpb cat_l3 cdp_l3 hw_pstate ssbd mba ibrs ibpb stibp vmmcall fsgsbase bmi1 avx2 smep bmi2 cqm rdt_a rdseed adx smap clflushopt clwb sha_ni xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local clzero irperf xsaveerptr rdpru wbnoinvd arat npt lbrv svm_lock nrip_save tsc_scale vmcb_clean flushbyasid decodeassists pausefilter pfthreshold avic v_vmsave_vmload vgif v_spec_ctrl umip rdpid overflow_recov succor smca
 bugs		: sysret_ss_attrs spectre_v1 spectre_v2 spec_store_bypass
 bogomips	: 4191.79
 TLB size	: 3072 4K pages
 clflush size	: 64
 cache_alignment	: 64
 address sizes	: 48 bits physical, 48 bits virtual
 power management: ts ttp tm hwpstate cpb eff_freq_ro [13] [14]
Python3Details: /usr/bin/python3.9, Python 3.9.5, python3-minimal, 3.9.4-1
PythonDetails: N/A
Registers:
 rax            0xad2e6c50e0595800  -5967713361602193408
 rbx            0x7f4213a22f90      139921773965200
 rcx            0x7f4213a22a90      139921773963920
 rdx            0x7f4213a22f10      139921773965072
 rsi            0x18017c7           25171911
 rdi            0x0                 0
 rbp            0x0                 0x0
 rsp            0x7fff061fe4d0      0x7fff061fe4d0
 r8             0x7f4213a22f90      139921773965200
 r9             0x7f4211d18090      139921743511696
 r10            0x0                 0
 r11            0x7f421339dfe0      139921767129056
 r12            0x18017c7           25171911
 r13            0x7f4211d18090      139921743511696
 r14            0x7f4213a22f10      139921773965072
 r15            0x7f4213a22a90      139921773963920
 rip            0x7f421339e012      0x7f421339e012 <XQueryTree+50>
 eflags         0x10202             [ IF RF ]
 cs             0x33                51
 ss             0x2b                43
 ds             0x0                 0
 es             0x0                 0
 fs             0x0                 0
 gs             0x0                 0
SegvAnalysis:
 Segfault happened at: 0x7f421339e012 <XQueryTree+50>:	mov    0x968(%rdi),%rax
 PC (0x7f421339e012) ok
 source "0x968(%rdi)" (0x00000968) not located in a known VMA region (needed readable region)!
 destination "%rax" ok
SegvReason: reading NULL VMA
SourcePackage: python3.9
Stacktrace:
 #0  0x00007f421339e012 in XQueryTree () from /lib/x86_64-linux-gnu/libX11.so.6
 No symbol table info available.
 #1  0x00007f4211d44249 in ?? () from /lib/x86_64-linux-gnu/libffi.so.8
 No symbol table info available.
 #2  0x00007f4211d43639 in ?? () from /lib/x86_64-linux-gnu/libffi.so.8
 No symbol table info available.
 #3  0x00007f4211d5d369 in ?? () from /usr/lib/python3.9/lib-dynload/_ctypes.cpython-39-x86_64-linux-gnu.so
 No symbol table info available.
 #4  0x00007f4211d5cca9 in ?? () from /usr/lib/python3.9/lib-dynload/_ctypes.cpython-39-x86_64-linux-gnu.so
 No symbol table info available.
 #5  0x0000000000521d6b in _PyObject_MakeTpCall ()
 No symbol table info available.
 #6  0x000000000051b595 in _PyEval_EvalFrameDefault ()
 No symbol table info available.
 #7  0x000000000052d163 in _PyFunction_Vectorcall ()
 No symbol table info available.
 #8  0x0000000000516543 in _PyEval_EvalFrameDefault ()
 No symbol table info available.
 ...
 #39 0x000000000061b724 in ?? ()
 No symbol table info available.
 #40 0x00000000006140df in PyRun_StringFlags ()
 No symbol table info available.
 #41 0x0000000000613acf in PyRun_SimpleStringFlags ()
 No symbol table info available.
 #42 0x00000000006135ce in Py_RunMain ()
 No symbol table info available.
 #43 0x00000000005ef7fd in Py_BytesMain ()
 No symbol table info available.
 #44 0x00007f4214b70565 in __libc_start_main (main=0x5ef7c0, argc=4, argv=0x7fff06200338, init=<optimised out>, fini=<optimised out>, rtld_fini=<optimised out>, stack_end=0x7fff06200328) at ../csu/libc-start.c:332
         self = <optimised out>
         result = <optimised out>
         unwind_buf = {cancel_jmp_buf = {{jmp_buf = {7003696, 2279199171758939812, 6223568, 0, 0, 0, -2279001928225628508, -2223231219582476636}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x4, 0x7fff06200338}, data = {prev = 0x0, cleanup = 0x0, canceltype = 4}}}
         not_first_call = <optimised out>
 #45 0x00000000005ef6fe in _start ()
 No symbol table info available.
StacktraceAddressSignature: /usr/bin/python3.9:11:/usr/lib/x86_64-linux-gnu/libX11.so.6.4.0+21012:/usr/lib/x86_64-linux-gnu/libffi.so.8.1.0+5249:/usr/lib/x86_64-linux-gnu/libffi.so.8.1.0+4639:/usr/lib/python3.9/lib-dynload/_ctypes.cpython-39-x86_64-linux-gnu.so+e369:/usr/lib/python3.9/lib-dynload/_ctypes.cpython-39-x86_64-linux-gnu.so+dca9:/usr/bin/python3.9+102d6b:/usr/bin/python3.9+fc595:/usr/bin/python3.9+10e163:/usr/bin/python3.9+f7543:/usr/bin/python3.9+10e163:/usr/bin/python3.9+f7543:/usr/bin/python3.9+f5a75:/usr/bin/python3.9+10e302:/usr/bin/python3.9+121211:/usr/bin/python3.9+f91b6
StacktraceTop:
 XQueryTree () from /lib/x86_64-linux-gnu/libX11.so.6
 ?? () from /lib/x86_64-linux-gnu/libffi.so.8
 ?? () from /lib/x86_64-linux-gnu/libffi.so.8
 ?? () from /usr/lib/python3.9/lib-dynload/_ctypes.cpython-39-x86_64-linux-gnu.so
 ?? () from /usr/lib/python3.9/lib-dynload/_ctypes.cpython-39-x86_64-linux-gnu.so
Tags:  hirsute wayland-session
ThreadStacktrace:
 .
 Thread 3 (Thread 0x7f4212e3f640 (LWP 12796)):
 #0  0x00007f4214c56b31 in __GI___select (nfds=4, readfds=0x7f4212e31070, writefds=0x7f4212e310f0, exceptfds=0x7f4212e31170, timeout=<optimised out>) at ../sysdeps/unix/sysv/linux/select.c:49
         sc_ret = -514
         sc_cancel_oldtype = 0
         sc_ret = <optimised out>
         ts64 = {tv_sec = 0, tv_nsec = 40642780}
         pts64 = <optimised out>
         r = <optimised out>
 #1  0x00000000006822d0 in ?? ()
 No symbol table info available.
 #2  0x000000000052de88 in ?? ()
 No symbol table info available.
 #3  0x000000000051b3ac in _PyEval_EvalFrameDefault ()
 No symbol table info available.
 #4  0x000000000052d163 in _PyFunction_Vectorcall ()
 No symbol table info available.
 ...
 #38 0x0000000000540211 in ?? ()
 No symbol table info available.
 #39 0x00000000006498da in ?? ()
 No symbol table info available.
 #40 0x0000000000641538 in ?? ()
 No symbol table info available.
 #41 0x00007f4214d3f450 in start_thread (arg=0x7f4212e3f640) at pthread_create.c:473
         ret = <optimised out>
         pd = 0x7f4212e3f640
         unwind_buf = {cancel_jmp_buf = {{jmp_buf = {139921761498688, 2279199171758939812, 140733296146318, 140733296146319, 0, 139921761498688, -2223245127582851420, -2223232071539728732}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
         not_first_call = 0
 #42 0x00007f4214c5fd53 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
 No locals.
 .
 Thread 2 (Thread 0x7f421256d640 (LWP 12797)):
 #0  0x00007f4214c56b31 in __GI___select (nfds=7, readfds=0x7f421256cc90, writefds=0x7f421256cd10, exceptfds=0x7f421256cd90, timeout=<optimised out>) at ../sysdeps/unix/sysv/linux/select.c:49
         sc_ret = -514
         sc_cancel_oldtype = 0
         sc_ret = <optimised out>
         ts64 = {tv_sec = 11809024, tv_nsec = 1}
         pts64 = <optimised out>
         r = <optimised out>
 #1  0x00007f42135f2e41 in ?? () from /lib/x86_64-linux-gnu/libtcl8.6.so
 No symbol table info available.
 #2  0x00007f4214d3f450 in start_thread (arg=0x7f421256d640) at pthread_create.c:473
         ret = <optimised out>
         pd = 0x7f421256d640
         unwind_buf = {cancel_jmp_buf = {{jmp_buf = {139921752249920, 2279199171758939812, 140733296145630, 140733296145631, 0, 139921752249920, -2223244123634245980, -2223232071539728732}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
         not_first_call = 0
 #3  0x00007f4214c5fd53 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
 No locals.
 .
 Thread 1 (Thread 0x7f4214b45740 (LWP 12795)):
 #0  0x00007f421339e012 in XQueryTree () from /lib/x86_64-linux-gnu/libX11.so.6
 No symbol table info available.
 #1  0x00007f4211d44249 in ?? () from /lib/x86_64-linux-gnu/libffi.so.8
 No symbol table info available.
 #2  0x00007f4211d43639 in ?? () from /lib/x86_64-linux-gnu/libffi.so.8
 No symbol table info available.
 #3  0x00007f4211d5d369 in ?? () from /usr/lib/python3.9/lib-dynload/_ctypes.cpython-39-x86_64-linux-gnu.so
 No symbol table info available.
 #4  0x00007f4211d5cca9 in ?? () from /usr/lib/python3.9/lib-dynload/_ctypes.cpython-39-x86_64-linux-gnu.so
 No symbol table info available.
 #5  0x0000000000521d6b in _PyObject_MakeTpCall ()
 No symbol table info available.
 ...
 No symbol table info available.
 #35 0x0000000000514a75 in ?? ()
 No symbol table info available.
 #36 0x000000000051480b in _PyEval_EvalCodeWithName ()
 No symbol table info available.
 #37 0x00000000005fb257 in PyEval_EvalCode ()
 No symbol table info available.
 #38 0x00000000006205fb in ?? ()
 No symbol table info available.
 #39 0x000000000061b724 in ?? ()
 No symbol table info available.
 #40 0x00000000006140df in PyRun_StringFlags ()
 No symbol table info available.
 #41 0x0000000000613acf in PyRun_SimpleStringFlags ()
 No symbol table info available.
 #42 0x00000000006135ce in Py_RunMain ()
 No symbol table info available.
 #43 0x00000000005ef7fd in Py_BytesMain ()
 No symbol table info available.
 #44 0x00007f4214b70565 in __libc_start_main (main=0x5ef7c0, argc=4, argv=0x7fff06200338, init=<optimised out>, fini=<optimised out>, rtld_fini=<optimised out>, stack_end=0x7fff06200328) at ../csu/libc-start.c:332
         self = <optimised out>
         result = <optimised out>
         unwind_buf = {cancel_jmp_buf = {{jmp_buf = {7003696, 2279199171758939812, 6223568, 0, 0, 0, -2279001928225628508, -2223231219582476636}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x4, 0x7fff06200338}, data = {prev = 0x0, cleanup = 0x0, canceltype = 4}}}
         not_first_call = <optimised out>
 #45 0x00000000005ef6fe in _start ()
 No symbol table info available.
Title: python3.9 crashed with SIGSEGV in XQueryTree()
UpgradeStatus: No upgrade log present (probably fresh install)
_MarkForUpload: True
separator: 
```

**Comment by TheLizzard** [comment]
After adding:
```
def destroy(self) -> None:
        self.root.destroy()
        XCloseDisplay(self.get_display())
```
It now crashes after 480 window creations/destructions

**Comment by TheLizzard** [comment]
Now the error is:
```
Maximum number of clients reachedMaximum number of clients reachedSegmentation fault (core dumped)
```

**Comment by TheLizzard** [comment]
The amount of windows that can be opened/closed doubled because all of the `NoTitlebarTk()` windows destroyed their `_XDisplay`s but all of the `NoTitlebarTk(master=...)` didn't because `tkinter` calls `<NoTitlebarTk>.root.destroy()` and not `<NoTitlebarTk>.destroy()`. So this is the solution that I came up with:

```python
class NoTitlebarTk:
    def __init__(self, master=None, **kwargs):
        ...
        self.root.destroy = self.destroy
    ...
    def destroy(self) -> None:
        XCloseDisplay(self.get_display())
        self.root.__class__.destroy(self)
    ...
```

**Comment by TheLizzard** [comment]
Now sometimes when running it through IDLE, it raises a `Tcl_AsyncDelete: async handler deleted by the wrong thread` error. But that is a bug in IDLE as I am not using threading or passing functions/tkinter variables into anything that uses threading. It runs fine from terminal.
