### ISSUE TITLE
Combobox causes unhandled exception

### ISSUE THREAD

**Issue by Dooez** [TheLizzard/BetterTk#2]
When using ttk.Combobox opening combobox causes unhandled exception:
Minimal code to reproduce
```Python
from src import *
import tkinter as tk
from tkinter import ttk

root = BetterTk()
dropdown = ttk.Combobox(root)
dropdown['values'] = ('value1', 'value2', 'value3')
dropdown.pack()

root.mainloop()
```
Exception:
```
Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib/python3.9/tkinter/__init__.py", line 1892, in __call__
    return self.func(*args)
  File "/home/timofey/Documents/BetterTk/src/bettertk/__init__.py", line 525, in window_unfocused
    if super().focus_displayof() is not None:
  File "/usr/lib/python3.9/tkinter/__init__.py", line 767, in focus_displayof
    return self._nametowidget(name)
  File "/usr/lib/python3.9/tkinter/__init__.py", line 1507, in nametowidget
    w = w.children[n]
KeyError: 'popdown'
```

**Comment by Dooez** [comment]
I think i've seen a Stackoverflow answer that this is a tkinter bug, but i am not an expert.

**Comment by Haris270** [comment]
You need to include the textvariable for the combobox.
```
root = BetterTk()
drop = tk.StringVar()
dropdown = ttk.Combobox(root, textvariable= drop)

```

**Comment by Dooez** [comment]
> You need to include the textvariable for the combobox.

Adding textvariable does not prevent exception. In case it did i think it would still be benefitial to handle exception.
Maybe adding `try... except...` block to `super().focus_displayof()` in `window_focused(...)` and `window_unfocused(..)` methods.
